#/bin/sh

if [ -z "$GOPATH" ]; then
    echo GOPATH environment variable not set
    exit
fi

if [ ! -e "$GOPATH/bin/2goarray" ]; then
    echo "Installing 2goarray..."
    go get github.com/cratonica/2goarray
    if [ $? -ne 0 ]; then
        echo Failure executing go get github.com/cratonica/2goarray
        exit
    fi
fi

convertImages(){
    echo "Converting $1"
    OUTPUT="icon_$1.go"
    echo Generating $OUTPUT
    echo "//go:build $1" > $OUTPUT
    echo "" >> $OUTPUT
    echo "package icon" >> $OUTPUT
    for file in $1/*
    do
        fname=${file##*/}
        fname=${fname%.*}
        echo $fname
        cat $file | $GOPATH/bin/2goarray $fname icon | grep -v "package icon" | grep -v "File generated by 2goarray" >> $OUTPUT
    done
}

convertImages "windows"
convertImages "darwin"
convertImages "linux"
