#!/bin/bash

# change access rights
sudo chgrp -R staff /Applications/Shieldoo\ Secure\ Network.app

# register service
sudo /Applications/Shieldoo\ Secure\ Network.app/Contents/MacOS/shieldoo-mesh-srv -desktop -service install

#start service
sudo /Applications/Shieldoo\ Secure\ Network.app/Contents/MacOS/shieldoo-mesh-srv -desktop -service start

exit 0
