name: Build

on:
  push:
    branches:
      - main
      - devel
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # build binaries
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
        # Whether to download only stable versions
        stable: true

    - name: prepare app version
      run: |
        export MYTAG="DEV"

    - name: Install packages gcc
      run: |
        sudo apt-get -y update || echo 0
        sudo apt-get -y install gcc libgtk-3-dev libappindicator3-dev || echo 0
    - name: Build clientapp
      run: |
        env GOOS=linux GOARCH=amd64 go build -tags=legacy_appindicator -ldflags "-X main.APPVERSION=$MYTAG -X main.ARCHITECTURE=amd64" -o ./out/asset/linux-amd64/shieldoo-mesh-app ./systray
        cp ./install/linux/linux-amd64-install.sh ./out/asset/linux-amd64/
        cp ./install/linux/logo.png ./out/asset/linux-amd64/
    - name: Build clientsrv
      run: |
        env GOOS=linux GOARCH=amd64 go build -ldflags "-X main.APPVERSION=$MYTAG -X main.ARCHITECTURE=amd64" -o ./out/asset/linux-amd64/shieldoo-mesh-srv 
        # FIX for nebula 1.9.3 os.Exit in code
        chmod +w /home/runner/go/pkg/mod/github.com/slackhq/nebula@v1.9.3/interface.go
        cat ./install/patch/interface.go > /home/runner/go/pkg/mod/github.com/slackhq/nebula@v1.9.3/interface.go
        env GOOS=linux GOARCH=amd64 go build -ldflags "-X main.APPVERSION=$MYTAG -X main.ARCHITECTURE=amd64" -o ./out/asset/linux-amd64/shieldoo-mesh-srv 
        env GOOS=linux GOARCH=arm GOARM=7  go build -ldflags "-X main.APPVERSION=$MYTAG -X main.ARCHITECTURE=arm7" -o ./out/asset/linux-arm7/shieldoo-mesh-srv 
        cp ./install/linux/linux-amd64-install-svc.sh ./out/asset/linux-amd64/
        cp ./install/linux/linux-arm7-install-svc.sh ./out/asset/linux-arm7/

    # build in docker
    - name: docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to container registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:dev
